include: [".htaccess"]

title: Victor Zamudio
url: "https://victorzamudio.info"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
